insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','straforini',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('gabriele','armanino',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('jacopo','dapueto',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('simone','campisi',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('alessandro','caroti',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','storace',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('elisa','zazzera',false);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','oneto',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('gabriele','gianluigino',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('jacopo','sivori',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('simone','mirto',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('alessandro','sabatini',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','squillante',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('elisa','montezemolo',true);