insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','straforini',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('gabriele','armanino',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('jacopo','dapueto',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('simone','campisi',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('alessandro','caroti',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','storace',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('elisa','zazzera',false);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','oneto',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('gabriele','gianluigino',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('jacopo','sivori',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('simone','mirto',true);
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('alessandro','sabatini',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('andrea','squillante',false );
insert into LATAZZASCHEMA.PERSONALE (nome,cognome,attivo) VALUES ('elisa','montezemolo',true);
insert into LATAZZASCHEMA.CIALDE (TIPO,PREZZO_EURO,PREZZO_CENTESIMI) VALUES ('caffè',0,5);
insert into LATAZZASCHEMA.CIALDE (TIPO,PREZZO_EURO,PREZZO_CENTESIMI) VALUES ('thè',0,5);
insert into LATAZZASCHEMA.CIALDE (TIPO,PREZZO_EURO,PREZZO_CENTESIMI) VALUES ('cioccolata',0,5);
insert into LATAZZASCHEMA.CIALDE (TIPO,PREZZO_EURO,PREZZO_CENTESIMI) VALUES ('tortaalgustoditorta',0,5);
insert into LATAZZASCHEMA.VISITATORE (NOME,COGNOME) VALUES ('pino','scotto');
insert into LATAZZASCHEMA.VISITATORE (NOME,COGNOME) VALUES ('luciano','ligabue');
insert into LATAZZASCHEMA.VISITATORE (NOME,COGNOME) VALUES ('salmo','lebon');
insert into LATAZZASCHEMA.VISITATORE (NOME,COGNOME) VALUES ('fabri','fibra');
insert into LATAZZASCHEMA.RIFORNIMENTO(DATAR,TIPO_CIALDA,NUMERO_CIALDE) VALUES ( '2000-12-31 00:00:00','caffè',2);
insert into LATAZZASCHEMA.RIFORNIMENTO(DATAR,TIPO_CIALDA,NUMERO_CIALDE) VALUES ( '2012-12-1 00:00:00','cioccolata',3);
insert into LATAZZASCHEMA.RIFORNIMENTO(DATAR,TIPO_CIALDA,NUMERO_CIALDE) VALUES ( '2012-12-10 00:00:00','thè',3);
insert into LATAZZASCHEMA.RIFORNIMENTO(DATAR,TIPO_CIALDA,NUMERO_CIALDE) VALUES ( '2012-11-1 00:00:00','thè',3);
COMMIT ;
insert into LATAZZASCHEMA.COMPRA_DIPENDENTE("NOME", "COGNOME", "CONTANTI", "NUMERO_CIALDE", "TIPO_CIALDA") VALUES ('andrea','straforini',false,10,'caffè');
insert into LATAZZASCHEMA.COMPRA_DIPENDENTE("DATA","NOME", "COGNOME", "CONTANTI", "NUMERO_CIALDE", "TIPO_CIALDA") VALUES ('2019-01-01 00:00:00','andrea','oneto',false,9,'caffè');
insert into LATAZZASCHEMA.COMPRA_VISITATORE("NOME", "COGNOME", "TIPO_CIALDA", "NUMERO_CIALDE") VALUES ('pino','scotto','caffè',6);
insert into LATAZZASCHEMA.COMPRA_VISITATORE("NOME", "COGNOME", "TIPO_CIALDA", "NUMERO_CIALDE") VALUES ('luciano','ligabue','thè',6);
insert into LATAZZASCHEMA.COMPRA_VISITATORE("DATA","NOME", "COGNOME", "TIPO_CIALDA", "NUMERO_CIALDE") VALUES ('2019-01-01 00:00:00','salmo','lebon','cioccolata',6);
